<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>test</string>
  </array>
  <key>name</key>
  <string>Mozilla Test Output</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>\bTEST-INFO\b</string>
      <key>name</key>
      <string>string</string>
    </dict>
    <dict>
      <key>match</key>
      <string>.*INFO TEST-END.*|.*TEST-START.*|\bTEST-PASS\b|\bTEST-KNOWN-FAIL\b</string>
      <key>name</key>
      <string>entity.name.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^\s*\b\d?\d:\d\d[:.]\d\d\b|\bINFO -</string>
      <key>name</key>
      <string>comment</string>
    </dict>
     <dict>
      <key>match</key>
      <string>\bEMITTING:</string>
      <key>name</key>
      <string>constant.numeric.css</string>
    </dict>
     <dict>
      <key>match</key>
      <string>\bDBG-FRONTEND:</string>
      <key>name</key>
      <string>support.function.function.js</string>
    </dict>
    <dict>
      <key>match</key>
      <string>WARNING:?</string>
      <key>name</key>
      <string>keyword</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(\+\+|--).*</string>
      <key>name</key>
      <string>comment</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\bJavaScript strict warning:.*</string>
      <key>name</key>
      <string>keyword</string>
    </dict>
    <dict>
      <key>match</key>
      <string>.*(exception:|JavaScript Error:|TEST-UNEXPECTED-FAIL|TEST-UNEXPECTED-PASS|DEBUG:|Stack trace:|Stack:|"debugger" keyword|doesn't exist:|console.error).*</string>
      <key>name</key>
      <string>invalid</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.mozillatest</string>
  <key>uuid</key>
  <string>ad841065-7197-4ca1-bd27-2568e7d7a658</string>
</dict>
</plist>
